from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"

include: "rules/qiime2_process.smk"
include: "rules/rmd_report.smk"

rule all:
	input:
		"index.html",

		"qiime2_process/sample-metadata.qzv",


		"qiime2_process/demux.qza",


		"qiime2_process/demux.qzv",


		"qiime2_process/rep-seqs.qza",
		"qiime2_process/feature-table.qza",
		"qiime2_process/stats.qza",


		"qiime2_process/rep-seqs.qzv",
		"qiime2_process/feature-table.qzv",
		"qiime2_process/stats.qzv",


 		"qiime2_process/feature-table-dn-99.qza",
		"qiime2_process/rep-seqs-dn-99.qza",


		"qiime2_process/table-cr-85.qza",
		"qiime2_process/rep-seqs-cr-85.qza",
		"qiime2_process/unmatched-cr-85.qza",


		"qiime2_process/table-or-85.qza",
		"qiime2_process/rep-seqs-or-85.qza",
		"qiime2_process/new-ref-seqs-or-85.qza",

		"qiime2_process/aligned-rep-seqs.qza",
		"qiime2_process/masked-aligned-rep-seqs.qza",
		"qiime2_process/masked-aligned-rep-seqs.qzv",

		"qiime2_process/transformed/feature-table.tsv",
		"qiime2_process/transformed/taxonomy.tsv",

		"qiime2_process/qiime2_composite.tsv",
	
